services:
  kazdy-dzien:
    build:
      context: .
      dockerfile: KazdyDzienZJezusem/Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"

  cloudflared:
    image: docker.io/cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
