services:
  kazdy-dzien:
    image: ghcr.io/tometchy/kazdydzienzjezusem:latest
    container_name: kazdy-dzien
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - ./:/data-out
