services:
  kazdy-dzien:
    image: ghcr.io/tometchy/kazdydzienzjezusem:latest
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - ./:/data-out

  cloudflared:
    image: docker.io/cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
